### ISSUE TITLE
SUSHI Tutorial - link for qualifications codes is broken - 404 error

### ISSUE THREAD

**Issue by analumonzon** [FSHSchool/site#58]
Click on: https://nucc.org/provider-taxonomy
I got this error message back:
![image](https://user-images.githubusercontent.com/10563947/158509094-2dd95035-6e7c-4047-9d00-2d877c436622.png)

**Comment by cmoesel** [comment]
Thanks for reporting this.  We'll look into it!

**Comment by jafeltra** [comment]
@analumonzon I took a look at this, and the URL you're referring to is actually intended to be used as the code system on a rule on the Veterinarian profile. Because code system are not required to resolve as URLs, this is actually okay. However, to make it more clear in the documentation, we updated the styling of the code system so it is more clear that it should be used with the FSH and is not a URL.
